POST http://localhost:5299/api/appointments/confirm?code=D71746C0-4749-4A89-B907-E0172A845348
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxNjQ3ZTU1Zi0zMmE3LTQzNTQtYmMxZC03ZjQxNGFmNGQwNTMiLCJyb2xlIjoiQWRtaW4iLCJuYmYiOjE3MTE2MzEwMTksImV4cCI6MTcxMTY1OTgxOSwiaXNzIjoiMTIzIiwiYXVkIjoiMTIzIn0.vmXnqnCBQ_pfiBF2nhiAaQYGljGHsftSdUeaCYRizIn--7E5r4oGsCGVry1sQoG7wOxyCA4_qrdg2WUGmZBysg
Content-Type: application/json