GET http://localhost:5299/api/appointments/A06D476D-695D-44FC-A46E-ADC20AA4A775
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxNjQ3ZTU1Zi0zMmE3LTQzNTQtYmMxZC03ZjQxNGFmNGQwNTMiLCJyb2xlIjoiQWRtaW4iLCJuYmYiOjE3MTE5MTA1NDQsImV4cCI6MTcxMTkzOTM0NCwiaXNzIjoiMTIzIiwiYXVkIjoiMTIzIn0.EuzLdflEP7hsZgPnBLHR1-kYJkFB3xqH4GqY-D9uURNq0r60HRdUmKTmkDL9WDEWjPHT2ZZT7GInJ-zFOaehIA
Content-Type: application/json

{
  "idDoctor": "A06D476D-695D-44FC-A46E-ADC20AA4A775"
}