POST http://localhost:5299/api/appointments
Content-Type: application/json

{
  "idDoctor": "1febd4e2-55ab-4cb2-b3cc-08dc4b3cd98d",
  "idPatient": "cf93c867-73fe-4d58-ada6-08dc4b3d0d82",
  "day": "2024-03-24",
  "start": "15:00:00",
  "end": "16:00:00"
}