GET http://localhost:5299/api/doctors/79A7B0B3-B5E5-42AC-A3D5-08F9139D945C
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjczMjI0OS1lZjY2LTQ4MjgtYjE0Yi1lNDEzMjUyYTVlZWMiLCJyb2xlIjoiQWRtaW4iLCJuYmYiOjE3MTIzMTY0NzgsImV4cCI6MTcxMjM0NTI3OCwiaXNzIjoiMTIzIiwiYXVkIjoiMTIzIn0.9gYISHkW9Tj4vzTsqbwjv947nRvsObNjQQ7QBjImytsMZVQ31WJ5_ZRv-24_YxjR0RTRaGQ1YckKOIk3X7sbZg
Content-Type: application/json

{
  "id": "79A7B0B3-B5E5-42AC-A3D5-08F9139D945C"
}
###