GET http://localhost:5299/api/patients
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJkMGY4ZmY4My01ZGQ3LTRjYzYtMDczYS0wOGRjNGMxM2M3NDgiLCJyb2xlIjoiQWRtaW4iLCJuYmYiOjE3MTEyOTMwODksImV4cCI6MTcxMTMxNDY4OSwiaXNzIjoiMTIzIiwiYXVkIjoiMTIzIn0.e8EtKWJi9Cjv_m2QdxugLkx-g_IfWqT8qkkFOJ0CzskERMHaS2lJyZzL1AJGfOp377BIz5AeXrW2pYKTFY5bDA
Accept: application/json
###